### ISSUE TITLE
`CreateDatasetUseCaseImpl`: allows create a dataset that has duplicate inputs

### ISSUE THREAD

**Issue by s373r** [kamu-data/kamu-cli#1051]
### Describe the bug

.

### Steps To Reproduce

1. Create a workspace
```shell
kamu init
```
2. Create snapshots with content:

```yaml
# root.yaml
kind: DatasetSnapshot
version: 1
content:
  name: root
  kind: Root
  metadata: [ ]
```

```yaml
# deriv.yaml
kind: DatasetSnapshot
version: 1
content:
  name: deriv
  kind: Derivative
  metadata:
    - kind: SetTransform
      inputs:
        - datasetRef: root
        - datasetRef: root
      transform:
        kind: Sql
        engine: some_engine
        queries:
          - query: select * from input
```

3. Add the snapshots to the workspace:
```shell
kamu add root.yaml
kamu add deriv.yaml
```

### Current Behavior

` deriv` added

### Expected Behavior

Error that `deriv` contains identical inputs (which 99% means copypaste error)

### kamu system info

```sh
The latest version at the moment (0.220.0)
```
