### ISSUE TITLE
Reset: Flatten metadata -- not only the last blocks are present after execution

### ISSUE THREAD

**Issue by s373r** [kamu-data/kamu-cli#1197]
### Describe the bug

The UI action description reads: `In this mode, reset will discard all data but retain the latest version of all metadata <CUT>`.
But after doing a reset, not only the latest versions of the blocks remain.

### Steps To Reproduce

1. Logging in https://platform.europort.kamu.dev/v/login
2. Create a dataset:
  ```yaml
kind: DatasetSnapshot
version: 1
content:
  name: kamu-cli-NNN
  kind: Root
  metadata:
    - kind: AddPushSource
      sourceName: default
      read:
        kind: NdJson
        schema:
          - "match_time TIMESTAMP"
          - "match_id BIGINT"
          - "player_id STRING"
          - "score BIGINT"
      merge:
        kind: Ledger
        primaryKey:
          - match_id
          - player_id
    - kind: SetVocab
      eventTimeColumn: match_time
  ```
3. Add another `AddPushSource` (duplicate) block via GQL:
```yaml
kind: MetadataEvent
version: 1
content:
  kind: AddPushSource
  sourceName: default
  read:
    kind: NdJson
    schema:
      - "match_time TIMESTAMP"
      - "match_id BIGINT"
      - "player_id STRING"
      - "score BIGINT"
  merge:
    kind: Ledger
    primaryKey:
      - match_id
      - player_id
```
GQL request:
```graphql
mutation {
  datasets {
    byId(datasetId: "did:odf:fed01e5b8d31521a79cd642d7bba873e0c48559f26f3c5deef29d43f42d8a4960ab1d") {
      metadata {
        chain {
          commitEvent(event: "kind: MetadataEvent\nversion: 1\ncontent:\n  kind: AddPushSource\n  sourceName: default\n  read:\n    kind: NdJson\n    schema:\n      - \"match_time TIMESTAMP\"\n      - \"match_id BIGINT\"\n      - \"player_id STRING\"\n      - \"score BIGINT\"\n  merge:\n    kind: Ledger\n    primaryKey:\n      - match_id\n      - player_id", eventFormat: YAML) {
            message
          }
        }
      }
    }
  }
}
```
4. Run `Reset: Flatten metadata`

PS. Example: https://platform.europort.kamu.dev/s373r/2025-04-14-root-2

### Current Behavior

Both `Push sources` are present

### Expected Behavior

That leaves only the last one

### kamu system info

```sh
kamuApiServer:
  enabled: false
  chart: kamu/kamu-api-server
  version: "0.62.0"

kamu-cli: 0.233.0
```
