### ISSUE TITLE
Invalid accountName in tokenstore after GH login

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-cli#267]
- Start a local `api-server` in a multi-tenant mode and a `web-ui`
- Run `kamu login --server http://localhost:8080`
- Login with github account
- Observe in `.kamu/.kamutokenstore`:
```yaml
kind: KamuTokenStore
version: 1
content:
- frontendUrl: http://localhost:4200/
  backendUrl: http://localhost:8080/
  tokens:
  - accountName: kamu
    accessToken: eyJ0e...mx
```

Here `accountName: kamu` is confusing. It should either reflect the account name of the logged in user (`sergiimk` in my case), or not be there at all (preferred, as it doesn't really serve any functional purpose - all we need is a token).
