### ISSUE TITLE
[4/7] Failed to update root dataset 

### ISSUE THREAD

**Issue by JvD007** [kamu-data/kamu-cli#32]
By testing kuma on a data set I got the following error, the kuma examples are working fine on my system.

$kamu-cli pull hydro.input.3
  [1/7] Checking for updates (hydro.input.3)
  Downloading hydro.input.3:
  [00:00:00] [##################################################################################################################################] 25.74KB/25.74KB (119.21MB/s, 0s)
  [4/7] **Failed to update root dataset** (hydro.input.3)
1 dataset(s) had errors

Summary of errors:

hydro.input.3: Ingest error: Engine error: Contract error: Engine did not write a response file, see log files for details: /home/jaco/.kamu/run/spark-jeCbeTBOlV.out.txt /home/jaco/.kamu/run/spark-jeCbeTBOlV.err.txt

Data set is locate at http://localhost/cameraregister-utrecht-csv.csv
I have add the csv file and the yaml file in the zip file 

I can't find what is going wrong with the csv file or yaml

Any help is welcome

[
[hydro-test.zip](https://github.com/kamu-data/kamu-cli/files/6278730/hydro-test.zip)

](url)

**Comment by sergiimk** [comment]
Hi @JvD007,

I think I reproduced your problem.

If you look at the stderr output of Spark (the second file the error message points to), in your case:
```
/home/jaco/.kamu/run/spark-jeCbeTBOlV.err.txt
```

You should see a pretty clear error message there:
```sql
Exception in thread "main" org.apache.spark.sql.catalyst.parser.ParseException: 
DataType varchar is not supported.(line 3, pos 29)

== SQL ==
SELECT
  `Naam` as naam,
  CAST(`Locatie (straat)` as VARCHAR) as straat,
-----------------------------^^^
  CAST(`Locatie (GPS Latitude)` as VARCHAR) as latitude,
  CAST(`Locatie (GPS Longtitude)` as VARCHAR) as longtitude,
  CAST(`Tijdigheid camera` as VARCHAR) as tijdigheid,
  CAST(`Eigenaar camera` as VARCHAR) as eigenaar,
  CAST(`Doel van de camera` as VARCHAR) as doel,
  CAST(`Tijdigheid camera` as VARCHAR) as tijdigheid,
  `Omschrijving` as mmschrijving
FROM input
```

I think `VARCHAR` is not a valid Spark SQL type, so when I replaced all its instances with `VARCHAR(50)` or a `STRING` this error goes away.

We will be improving error reporting very soon to make defining a new dataset much less painful.

**Comment by sergiimk** [comment]
Here's a fully working dataset definition for your data:

> You will need latest `kamu` version `0.38.1` for this to work, as there was a bug with how spaces in column names are handled

```yaml
apiVersion: 1
kind: DatasetSnapshot
content:
  id: hydro.input.3
  source:
    kind: root
    fetch:
      kind: url
      url: file:///home/.../cameraregister-utrecht-csv.csv
    read:
      kind: csv
      separator: ';'
      header: true
      nullValue: ''
    preprocess:
        kind: sql
        engine: spark
        query: >
          SELECT
            current_timestamp() as event_time,
            `Naam` as naam,
            CAST(`Locatie (straat)` as VARCHAR(50)) as straat,
            CAST(`Locatie (GPS Latitude)` as VARCHAR(50)) as latitude,
            CAST(`Locatie (GPS Longtitude)` as VARCHAR(50)) as longtitude,
            CAST(`Tijdigheid camera` as VARCHAR(50)) as tijdigheid,
            CAST(`Eigenaar camera` as VARCHAR(50)) as eigenaar,
            CAST(`Doel van de camera` as VARCHAR(50)) as doel,
            `Omschrijving` as mmschrijving
          FROM input
    merge:
      kind: ledger
      primaryKey:
      - naam
```
Few things to notice here:

Just in case you didn't know you can use `file:///home/.../cameraregister-utrecht-csv.csv` style of URLs to point at local files without needing to host them on `localhost`.

Also notice that I'm adding `current_timestamp() as event_time` column. The reason is that `kamu` is a stream processing system that works in event time space, so `event_time` column is required. If this sounds confusing - see [this presentation](https://www.youtube.com/watch?v=-3IMm7wtlO0).

Since your data doesn't have a time column - I added `event_time` artificially from `current_timestamp()`. But this may indicate that your data is not actually of type `ledger` (see this description of [Merge Strategies](https://github.com/kamu-data/open-data-fabric/blob/master/open-data-fabric.md#merge-strategies)).

Hope this helps.

I'll close this issue now, but please re-open if needed.
