### ISSUE TITLE
How to use ODS

### ISSUE THREAD

**Issue by JvD007** [kamu-data/kamu-cli#40]
Lots of open data sets are using or are based on ODS - OpenDocument Spreadsheet, organizations like the Dutch government is moving into that direction.

Example:
Download: [https://rijksfinancien.nl/bestanden/agentschappen_rijksfinancien_nl.ods ](https://rijksfinancien.nl/bestanden/agentschappen_rijksfinancien_nl.ods )

Is it possible to use this type off files!

**Comment by JvD007** [comment]
Second, what to do with open datasets based on:

OData 3.0 and 4.0 Protocol

See [https://www.cbs.nl/en-gb/onze-diensten/open-data/statline-as-open-data](https://www.cbs.nl/en-gb/onze-diensten/open-data/statline-as-open-data)

**Comment by sergiimk** [comment]
For ODS (which is similar to Excel format) in general this is a really poor format for data publishers to use:
* It can contain multiple sheets
* Is basically schema-less:
  * Different rows can contain different number of values
  * Columns are not restricted to the same type

This is not a structured data format... only slightly better than publishing data in PDFs :(

So ideally data publishers should be informed about the limitations of such formats and convinced to change.

On `kamu` side you the best you could do is to use [pipe-based preparation steps](https://github.com/kamu-data/kamu-cli/blob/master/examples/currency_conversion/io.exchangeratesapi.daily.usd-cad.yaml#L10-L15) to run some script that can convert the ODS file into CSV or JSON (example I linked is piping data into `jq` and transforms it). 

Here's a [thread about tools](https://askubuntu.com/questions/1042624/how-to-split-an-ods-spreadsheet-file-into-csv-files-per-sheet-on-the-terminal) that might be able to help with that.

**Comment by sergiimk** [comment]
OData is basically JSON over HTTP, so if you have a URL that returns the entire dataset as a JSON array of objects - you can [use `jq` command](https://github.com/kamu-data/kamu-cli/blob/master/examples/currency_conversion/io.exchangeratesapi.daily.usd-cad.yaml#L10-L15) to transform it into desired schema.

If you send us a link to the dataset you're trying to import we can try to help.

The only reason I can think of to add support for OData is if the dataset is so big that it cannot be returned in a single response, and requires you to iterate through multiple "pages" of results to get all data. If that's the case - we can support it fairly easily.

**Comment by JvD007** [comment]
OData Goverment site: [https://opendata.cbs.nl/statline/portal.html?_la=en&_catalog=CBS&tableId=84166ENG&_theme=1079](https://opendata.cbs.nl/statline/portal.html?_la=en&_catalog=CBS&tableId=84166ENG&_theme=1079)

OData url: https://opendata.cbs.nl/ODataApi/odata/84166ENG

As an example

**Comment by sergiimk** [comment]
Hi @JvD007 

As I mentioned before, ingesting OData datasets using `jq` to flatten the data seems to work fine. Here's a dataset manifest that ingests the dataset you've provided:

```yaml
apiVersion: 1
kind: DatasetSnapshot
content:
  id: nl.cbs.opendata.employment.84166eng
  source:
    kind: root
    fetch:
      kind: url
      url: https://opendata.cbs.nl/ODataApi/odata/84166ENG/TypedDataSet
    prepare:
    - kind: pipe
      command:
      - 'jq'
      - '-r'
      - '.value[] | [.ID, .EmploymentType, .SectorBranchesSIC2008, .Periods, .EmployedPersons_1, .EmployedPersonsSeasonalAdjusted_2, .Jobs_3, .JobsSeasonalAdjusted_4, .HoursWorked_5, .HoursWorkedSeasonalAdjusted_6, .EmployedPersons_7, .Jobs_8, .EmployedPersonsSeasonalAdjusted_9, .JobsSeasonalAdjusted_10] | @csv'
    read:
      kind: csv
      header: false
      schema:
      - ID BIGINT
      - EmploymentType STRING
      - SectorBranchesSIC2008 STRING
      - Periods STRING
      - EmployedPersons_1 DOUBLE
      - EmployedPersonsSeasonalAdjusted_2 DOUBLE
      - Jobs_3 DOUBLE
      - JobsSeasonalAdjusted_4 DOUBLE
      - HoursWorked_5 DOUBLE
      - HoursWorkedSeasonalAdjusted_6 DOUBLE
      - EmployedPersons_7 DOUBLE
      - Jobs_8 DOUBLE
      - EmployedPersonsSeasonalAdjusted_9 DOUBLE
      - JobsSeasonalAdjusted_10 DOUBLE
    merge:
      kind: snapshot
      primaryKey:
      - ID
```

It's a little verbose, but should work fine for now. I'll ticket up improving the ingest experience of the JSON documents.

I have also started compiling a [list of examples](https://github.com/kamu-data/kamu-cli/blob/master/docs/ingest_examples.md) of ingesting some of the common data formats.
