### ISSUE TITLE
Containerized ingestion: iterative reading fail on the second iteration (DataFusion engine)

### ISSUE THREAD

**Issue by s373r** [kamu-data/kamu-cli#402]
## Specifications
- `kamu-cli` version: latest

## Steps to Reproduce the Problem
1. Use the following dataset spec (https://github.com/kamu-data/kamu-contrib/pull/13):
```yaml
---
kind: DatasetSnapshot
version: 1
content:
  name: net.rocketpool.reth.mint-burn
  kind: root
  metadata:
    - kind: setPollingSource
      fetch:
        kind: container
        image: "ghcr.io/kamu-data/fetch-net.rocketpool.reth.mint-burn:0.2.0"
        env:
          - name: ETH_NODE_PROVIDER_URL
          - name: BLOCK_BATCH_SIZE
            value: "10000"
          - name: ODF_BATCH_SIZE
            value: "100000"
      read:
        kind: ndJson
      preprocess:
        kind: sql
        engine: datafusion
        query: |
          SELECT
            'rETH' as token_symbol,
            "eventName" as event_name,
            cast("amount" as double) / pow(10.0, 18) as amount,
            cast("ethAmount" as double) / pow(10.0, 18) as eth_amount,
            "blockNumber" as block_number,
            "blockHash" as block_hash,
            to_timestamp_seconds("eventTime") as event_time,
            "transactionIndex" as transaction_index,
            "transactionHash" as transaction_hash,
            "logIndex" as log_index
          FROM input
      merge:
        kind: ledger
        primaryKey:
          - transaction_hash
    - kind: setVocab
      eventTimeColumn: block_time
```
2. Try to pull the dataset:
```shell
rm -rf .kamu \ 
    && kamu init \
    && kamu add . -r \
    && ETH_NODE_PROVIDER_URL=<INSERT_YOUR_VALUE> kamu pull --all
```

## Expected Behavior
Execute without errors

## Actual Behavior
Trimmed output:
```
BatchError(BatchError { summary: "Failed to update 1 dataset(s)", errors_with_context: [(PollingIngestError(EngineError(InternalError(InternalEngineError { source: InternalError { source: Execution("The table input already exists"), backtrace: Some(Backtrace [{ fn: "internal_error::InternalError::new", file: "/home/s373r/src/work/kamu-data/kamu-cli/src/utils/internal-error/src/lib.rs", line: 38 }, { fn: "<E as internal_error::ErrorIntoInternal>::int_err", file: "/home/s373r/src/work/kamu-data/kamu-cli/src/utils/internal-error/src/lib.rs", line: 56 }, ...
```
