### ISSUE TITLE
Missed last writes: unflushed `tokio::fs::file`'s

### ISSUE THREAD

**Issue by s373r** [kamu-data/kamu-cli#404]
## Context

`tokio::fs::file` is NOT flushed during `Drop` (like `std::fs::file`) regarding async mature of processing (https://github.com/tokio-rs/tokio/issues/2307#issuecomment-596336451)

## Specifications
- `kamu-cli` version: latest

## Steps to Reproduce the Problem
1. Use the following dataset spec (https://github.com/kamu-data/kamu-contrib/pull/13):
```yaml
---
kind: DatasetSnapshot
version: 1
content:
  name: net.rocketpool.reth.mint-burn
  kind: root
  metadata:
    - kind: setPollingSource
      fetch:
        kind: container
        image: "ghcr.io/kamu-data/fetch-net.rocketpool.reth.mint-burn:0.2.0"
        env:
          - name: ETH_NODE_PROVIDER_URL
          - name: BLOCK_BATCH_SIZE
            value: "100000"
          - name: ODF_BATCH_SIZE
            value: "100000"
      read:
        kind: ndJson
      preprocess:
        kind: sql
        engine: datafusion
        query: |
          SELECT
            'rETH' as token_symbol,
            "eventName" as event_name,
            cast("amount" as double) / pow(10.0, 18) as amount,
            cast("ethAmount" as double) / pow(10.0, 18) as eth_amount,
            "blockNumber" as block_number,
            "blockHash" as block_hash,
            to_timestamp_seconds("eventTime") as event_time,
            "transactionIndex" as transaction_index,
            "transactionHash" as transaction_hash,
            "logIndex" as log_index
          FROM input
      merge:
        kind: ledger
        primaryKey:
          - transaction_hash
    - kind: setVocab
      eventTimeColumn: block_time
```
2. Patch the image (look at `./src/app.ts`):
```diff
- const ethHeadBlock = await provider.getBlockNumber();
+ const ethHeadBlock = 18877931;
```
3. Pull the dataset::
```shell
rm -rf .kamu \ 
    && kamu init \
    && kamu add . -r \
    && ETH_NODE_PROVIDER_URL=<INSERT_YOUR_VALUE> kamu pull --all \
    && wc -l .kamu/cache/fetch-*
```

**⚠️ Other similar places should be covered**

## Expected Behavior
```
   38564 .kamu/cache/fetch-<RANDOM VALUES>
```

## Actual Behavior
- Any other results
