### ISSUE TITLE
Unable to open the GraphQL playground in a multitenant workspace

### ISSUE THREAD

**Issue by s373r** [kamu-data/kamu-cli#417]
## Specifications
- `kamu-cli` version: `0.150.1`

## Steps to Reproduce the Problem
1. Create a kamu workspace
```shell
kamu init
```
2. Use the following workspace config (`.kamu/workspace.config`)
```yaml
---
kind: WorkspaceConfig
version: 1
content:
  multi_tenant: true
```
3. Use the following kamu config (`.kamu/.kamuconfig`)
```yaml
---
kind: CLIConfig
version: 1
content:
  engine:
    runtime: podman
  users:
    predefined:
      - accountId: 1
        accountName: acc1
        displayName: Юзер Юзерович
        accountType: User
        avatarUrl: https://avatars.githubusercontent.com/u/50896974?s=200&v=4
      - accountId: 2
        accountName: acc2
        displayName: Пользователь Пользовишлили
        accountType: User
        avatarUrl: https://avatars.githubusercontent.com/u/50896974?s=200&v=4
      - accountId: 3
        accountName: acc3
        displayName: Аккаунт Аккаунтоненко
        accountType: User
        avatarUrl: https://avatars.githubusercontent.com/u/50896974?s=200&v=4
      - accountId: 1337
        accountName: s373r
        displayName: Дима Приступа
        accountType: User
        avatarUrl: https://avatars.githubusercontent.com/u/50896974?s=200&v=4
        # isAdmin: true
```
4. Start API server
```shell
KAMU_JWT_SECRET=<YOUR_VALUE> \
KAMU_AUTH_GITHUB_CLIENT_ID=<YOUR_VALUE> \ 
KAMU_AUTH_GITHUB_CLIENT_SECRET=<YOUR_VALUE> \
    kamu system api-server --http-port 8080
```
5. Start `kamu-web-ui` web-server (https://github.com/kamu-data/kamu-web-ui)
```shell
npm start # at `kamu-web-ui` repo
```
6. Open http://localhost:4200/graphql

## Expected Behavior
GraphQL playground opened

## Actual Behavior
A "user" page opened
![image](https://github.com/kamu-data/kamu-cli/assets/29308899/d738c095-7a9f-4314-93d1-cee4f6b10568)
