### ISSUE TITLE
Broken dataset list GraphQL response

### ISSUE THREAD

**Issue by s373r** [kamu-data/kamu-cli#420]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### kamu version

```sh
appVersion: 0.150.1
buildTimestamp: 2024-01-08T14:08:50.439314965Z
gitDescribe: v0.148.0-32-g1f10c31d
gitSha: 1f10c31d155dc9d10bf5ff59b88048ece70d971c
gitCommitDate: 2024-01-08
gitBranch: feature/introduce-admin-users
rustcSemver: 1.76.0-nightly
rustcChannel: nightly
rustcHostTriple: x86_64-unknown-linux-gnu
rustcCommitSha: 90e321d82a0a9c3d0e3f180d4d17541b729072e0
cargoTargetTriple: x86_64-unknown-linux-gnu
cargoFeatures: default
cargoOptLevel: '0'
```

### Describe the bug

Querying all datasets from `kamu-web-ui` (main page) does not work

(Due to uninitialized `DependencyGraphServiceInMemory::State::dataset_node_indices` for existing datasets)

### Steps To Reproduce

1. Create a kamu workspace
```shell
kamu init
```
2. Use the following workspace config (`.kamu/workspace.config`)
```yaml
---
kind: WorkspaceConfig
version: 1
content:
  multi_tenant: true
```
3. Use the following kamu config (`.kamu/.kamuconfig`)
```yaml
---
kind: CLIConfig
version: 1
content:
  engine:
    runtime: podman
  users:
    predefined:
      - accountId: 1
        accountName: acc1
        displayName: Юзер Юзерович
        accountType: User
        avatarUrl: https://avatars.githubusercontent.com/u/50896974?s=200&v=4
      - accountId: 2
        accountName: acc2
        displayName: Пользователь Пользовишлили
        accountType: User
        avatarUrl: https://avatars.githubusercontent.com/u/50896974?s=200&v=4
      - accountId: 3
        accountName: acc3
        displayName: Аккаунт Аккаунтоненко
        accountType: User
        avatarUrl: https://avatars.githubusercontent.com/u/50896974?s=200&v=4
      - accountId: 1337
        accountName: s373r
        displayName: Дима Приступа
        accountType: User
        avatarUrl: https://avatars.githubusercontent.com/u/50896974?s=200&v=4
        # isAdmin: true
```
4. Start API server
```shell
KAMU_JWT_SECRET=<YOUR_VALUE> \
KAMU_AUTH_GITHUB_CLIENT_ID=<YOUR_VALUE> \ 
KAMU_AUTH_GITHUB_CLIENT_SECRET=<YOUR_VALUE> \
    kamu system api-server --http-port 8080
```
5. Start `kamu-web-ui` web-server (https://github.com/kamu-data/kamu-web-ui)
```shell
npm start # at `kamu-web-ui` repo
```
6. Create several datasets via `kamu-web-ui` (http://localhost:4200)
7. Restart the server
8. Reopen main page (http://localhost:4200)

### Current Behavior

Broken main page

### Expected Behavior

A list of all available datasets is displayed

### Logs

```
[2024-01-08T14:18:51.574Z] ERROR: kamu/188231 on v01d: [GQL_REQUEST - EVENT] Unhandled error (file=src/adapter/graphql/src/extensions.rs,line=45,target=kamu_adapter_graphql::extensions)
    error_backtrace:    0: internal_error::InternalError::new
                 at ./src/utils/internal-error/src/lib.rs:38:18
       1: <E as internal_error::ErrorIntoInternal>::int_err
                 at ./src/utils/internal-error/src/lib.rs:56:9
       2: <core::result::Result<OK,E> as internal_error::ResultIntoInternal<OK>>::int_err
                 at ./src/utils/internal-error/src/lib.rs:71:27
       3: kamu_adapter_graphql::queries::datasets::dataset_metadata::DatasetMetadata::current_downstream_dependencies::{{closure}}
                 at ./src/adapter/graphql/src/queries/datasets/dataset_metadata.rs:129:46
       4: <kamu_adapter_graphql::queries::datasets::dataset_metadata::DatasetMetadata as async_graphql::resolver_utils::container::ContainerType>::resolve_field::{{closure}}::{{closure}}
                 at ./src/adapter/graphql/src/queries/datasets/dataset_metadata.rs:22:1
       5: <kamu_adapter_graphql::queries::datasets::dataset_metadata::DatasetMetadata as async_graphql::resolver_utils::container::ContainerType>::resolve_field::{{closure}}
                 at ./src/adapter/graphql/src/queries/datasets/dataset_metadata.rs:22:1
<CUT>
```

### Anything else?

![image](https://github.com/kamu-data/kamu-cli/assets/29308899/e5b9ae8c-4a2e-4ef2-8d9a-5c4b01338106)
