### ISSUE TITLE
Add implicit `User-Agent` header for HTTP requests

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-cli#656]
### Describe the bug

Some platforms like GitHub API require `User-Agent` header to be set, otherwise they fail with 403. CLI currently does not set this header at all.

### Steps To Reproduce

Example dataset:
```yaml
kind: DatasetSnapshot
version: 1
content:
  name: com.github.kamu-cli.views
  kind: Root
  metadata:
    - kind: SetPollingSource
      fetch:
        kind: Url
        url: https://api.github.com/repos/kamu-data/kamu-cli/traffic/views
        headers:
          - name: Authorization
            value: Bearer gho_xxx
      read:
        kind: Json
        subPath: views
      merge:
        kind: Append
```
Substitute auth with your own token and you still will get 403 error on pull.

### Current Behavior

No `User-Agent` header is sent. Error disappears if you add the header explicitly:
```yaml
headers:
  - name: User-Agent
    value: kamu
```

### Expected Behavior

CLI should always send this header as:
```
User-Agent: dev.kamu.cli/major.minor.patch
```

### kamu system info

```sh
-
```
