### ISSUE TITLE
Support default values in dataset env var templates

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-cli#828]
Currently we allow ingest parametrization via env vars that are templated into value strings like so:
```yaml
fetch:
  kind: Container
  image: "ghcr.io/kamu-data/fetch-com.defillama:0.1.0"
  args:
    - --request-interval
    - '${{ env.request_interval }}'
    - protocols
    - chain-tvls
    - --top-n
    - '${{ env.top_n_protocols }}'
```

It would be very useful to allow dataset manifests to provide default values for parameters that are not specified (e.g. using a syntax similar to GitHub's templating engine):

```yaml
fetch:
  kind: Container
  image: "ghcr.io/kamu-data/fetch-com.defillama:0.1.0"
  args:
    - --request-interval
    - '${{ env.request_interval || 1 }}'
    - protocols
    - chain-tvls
    - --top-n
    - '${{ env.top_n_protocols || 10 }}'
```
