### ISSUE TITLE
Ingest: Support S3 bucket in `FilesGlob` source

### ISSUE THREAD

**Issue by sergiimk** [kamu-data/kamu-cli#943]
This ticket is to extend `FilesGlob` support to allow something like:
```yaml
fetch:
  kind: FilesGlob
  path: s3://my.bucket/data/db-table-dump-*.csv
  eventTime:
    kind: FromPath
    pattern: 'db-table-dump-(\d+-\d+-\d+)\.csv'
    timestampFormat: '%Y-%m-%d'
```
It should also allow expressing paths to S3-like storages like Minio e.g. like:
```
s3+http://localhost:5050/my.bucket/data/db-table-dump-*.csv
```

Notes:
- Wildcards will only be supported in object path components (not hosts or bucket names)
- We can support initially patterns like (`/dir/file-*.csv`, `/dir/**/*.json`, `/dir/subdir-*/*.parquet`)
- This type of ingest is aimed at initial convenience only, and should be reserved for low file counts, as the operation of listing an S3 bucket may get slow/expensive at scale
- Similarly to existing `FileGlob` logic, the state of the source will be represented by the name of the last file ingested, with ingest proceeding in lexicographic sort order
